### ISSUE TITLE
服务端数据库端口开放出现问题

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/service-end#10]
// 通过以下url连接服务端数据库
url := fmt.Sprintf("root:root@tcp(119.29.155.194:5000)/activityplus?charset=utf8")

// 服务端数据库连接不上
dial tcp [::1]:3306: connectex: No connection could be made because the target machine actively refused it.

**Comment by TXZdream** [comment]
我也不知道什么原因，因为我从来没有成功用我的代码连接过，你试一下第三方软件能不能用，如果不行的话我找时间处理一下

**Comment by iamxiaoyubei** [comment]
我上星期连接正常，昨天晚上连不上了

**Comment by iamxiaoyubei** [comment]
你说的第三方软件是指？

**Comment by TXZdream** [comment]
比如workbrench

**Comment by iamxiaoyubei** [comment]
???我说的是服务端你在5000端口开放出来的那个数据库，不是说本地数据库

**Comment by iamxiaoyubei** [comment]
是不是数据库服务在那个端口关闭了？或者firewall挡住了？
