### ISSUE TITLE
关于服务器资源的问题

### ISSUE THREAD

**Issue by TXZdream** [SYSU-ActivityPlusPC/service-end#11]
现在的服务器是1核1g，主要的大型应用如下：
1. 数据库，该应用占据了大部分内存，曾尝试开两个数据库，发现内存就会爆掉
2. rabbitmq，不是很了解，但是应该也是罪魁祸首之一，不过我把该容器停止之后，服务器的内存空出了100m左右
初步有两个解决方案：
1. 更改架构，既然再加上消息队列会导致服务器卡顿，那就想办法把消息队列去掉就好了，比如退而求其次，将邮件发送的改成进程间通信，但是可能会带来扩展性的问题，不过要是考虑流量不是很大的话，我觉得这样是可以的
2. 配置什么的其实我是觉得没啥必要的，毕竟觉得除了特殊情况，否则资源不太会出现不够的情况，而且目前是开发阶段，也不是到了不能用的情况，所以提高容量的建议觉得不采纳
代码什么的，先做出一个可用的版本，之后再去重构什么的，觉得也不是不可以，毕竟，先做出，再做好

**Comment by iamxiaoyubei** [comment]
更改架构由你决定
配置也可以升级，只要需要的话
