### ISSUE TITLE
第四次后端开发验收测试

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/service-end#12]
@TXZdream 
- [x] PCUserList: **type==1时返回注册申请列表(含有待审核和已拒绝活动列表)**,返回错误

- [x] PC Signup注册API多次重复注册某个已通过审核的邮箱的用户时，返回400，但是数据库中写入了注册用户，可能是邮箱查重部分出了问题，可能是虽查重但未禁止写入数据库

- [x] 注册并且审核通过后，用户无法成功登陆（以下为登陆的body），返回400，可能是因为没有邮箱查重？**后端数据库中联系邮箱需设置为unique，邮箱不能够存在重复的情况在提交注册时就需要进行检查，只需要检测与已审核通过的账号邮箱是否重复即可**
```
{
    "account": "394634397@qq.com",
    "password": "5ed3b0bb42dc0f31f42cd1e7d48daddb"
}
```

- [x] 审核PCuserAPI：https://www.sysuactivity.com/api/pcusers?id=8&verify=2 ， 并未成功拒绝该用户，返回400，也没有发送拒绝信息到邮箱

- [x] pcuser的register_time出现错误，与注册的时间/审核通过的真实时间不一致，如我是19：12注册的，但是显示的是十点多

**Comment by iamxiaoyubei** [comment]
@TXZdream 
你可以测试我的API部分，如果有什么错误，也欢迎反馈指出

**Comment by TXZdream** [comment]
时间貌似是容器的时间和时区问题，这个晚些时候修补

**Comment by iamxiaoyubei** [comment]
@TXZdream 
成功通过测试
