### ISSUE TITLE
第五次迭代后端任务

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/service-end#13]
@TXZdream 三个API

- [x] List required actApply

- [x] Delete ActApply By Club

- [x] Close Activity Apply By Club

@iamxiaoyubei 三个API

- [x] List required activities By Club

- [x] Modify Activity Info By Manager or Club

- [x] Get The number of Activity Status By Club

迭代DDL：6月14日，下周星期四

**Comment by iamxiaoyubei** [comment]
@TXZdream 你那部分的权限访问"仅社团可访问，并且需要检查活动actId是否为本社团发布的活动，仅本社团发布的活动才能够通过权限，否则没有权限401"的相关函数已实现：**model.IsPublishedByClub(userId, intActId)**，使用可参考：

```
				pathArr := strings.Split(path, "/")
				actId := pathArr[2]
				intActId, err := strconv.Atoi(actId)
				if err != nil {
					fmt.Fprint(os.Stderr, err)
					rw.WriteHeader(400)
					return
				}

				yes, _ := model.IsPublishedByClub(userId, intActId)
				if yes {
					next(rw, r)
					return
				} else {
					rw.WriteHeader(401)
					return
				}
```

**Comment by iamxiaoyubei** [comment]
已通过本地测试，麻烦 @TXZdream 提交到服务器上让我进行一下服务器测试~谢谢~

**Comment by TXZdream** [comment]
已部署

**Comment by TXZdream** [comment]
@iamxiaoyubei 问一下，貌似actApply表没有applyid哎……这个怎么处理？

**Comment by iamxiaoyubei** [comment]
@TXZdream  给actapply表加上id，把小程序的xorm表也改一下，加上id不会对小程序造成影响的。

**Comment by TXZdream** [comment]
ok

**Comment by TXZdream** [comment]
完成服务端接口测试，未发现异常
