### ISSUE TITLE
第五次后端验收测试

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/service-end#14]
@TXZdream 

- [x] **Close Activity Apply By Club**

https://www.sysuactivity.com/api/act/71
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1Mjk4NTUyNzYsImlhdCI6MTUyODY0NTY3Niwic3ViIjoieGlhb3liNUBtYWlsMi5zeXN1LmVkdS5jbiJ9.EXzIdbJuBiC3QCj6K4tbMFrg9qivAhx8_oYUJuKLh8w

出现400
这个活动是pcuserid7发布的，上面的token也是7的，并且其他的API是通过了权限正确的

- [x] **Delete ActApply**

无论是删除一个不存在的actapply还是actapply不是对应actid的actapply，返回的都是200，同时数据库也不会改变

希望：不存在的返回204，就我上面说的两种都算不存在，搜索时表中actid==**&&actapplyid==**搜不到返回一下204就好，数据库不更改

**Comment by TXZdream** [comment]
第一个问题，我注册一个全新账户并进行验证，最后结果表明时可以关闭的，请确定token是否正确；
第二个问题已解决
