### ISSUE TITLE
完成第一次迭代的发布活动API

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/service-end#2]

**Comment by TXZdream** [comment]
已经完成，本地手动测试通过，需要注意的问题：
1. 时间格式的问题，原api中的时间格式是有问题的，这里改成了字符串类型进行解析
2. 时间的不一致问题，即解析的时候和存储的时间所在的时区貌似不同，这个暂时影响不大，但需要谨慎
