### ISSUE TITLE
完成第二次迭代的发布活动API

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/service-end#3]

**Comment by TXZdream** [comment]
提交到后台用以更改的数据需包含所有信息，或在文档中指明需要修改的字段，现有的后台是直接将前端发来的数据进行完全覆盖

**Comment by TXZdream** [comment]
本地已完成代码及基本测试，等待检查

**Comment by iamxiaoyubei** [comment]
- [ ] 经测试发现list all activity和activity详情api小程序和PC端并不能够共用：https://www.sysuactivity.com/api/act?page={pagenum} 需要根据verified进行有选择地返回，请参考新的API和技术文档，返回的参数也进行了相应的修改；https://www.sysuactivity.com/api/act/actid 则无论verified通过与否均返回活动详情，因此需要修改一下。

- [ ] API错误返回信息不够详尽，等待后续迭代修正还是添加多几个错误码进行说明？

**Comment by TXZdream** [comment]
1. 小程序端和pc端的接口是独立的，因此不存在`[GET /api/act]`这么个接口，这个接口时小程序端编写的，因此需要调用[GET /act]
2. 原则上说act的增删该查应该属于同一个服务，但是由于pc和小程序的分离，所以需要划分不同的路径下，还请谅解，暂时没有特别好的解决方案
3. 关于verified的问题，之前时由于测试需要去除了verified属性，现已修复，即只会返回认证通过的活动

**Comment by iamxiaoyubei** [comment]
可以放到下一次迭代，这两个API按照上面说的来，以及参考新的API和技术文档，在PC后端增加活动列表和活动详情的API即可，这两个API和小程序端略有不同，但是大部分代码一样的。

**Comment by TXZdream** [comment]
已经提交并在本地进行了简单测试

**Comment by iamxiaoyubei** [comment]
获取活动列表API：https://www.sysuactivity.com/api/act?page={pagenum}&verify={verified} 返回的response json 属性出现错误，请仔细查看API返回的属性是哪几个

**Comment by TXZdream** [comment]
当前的返回顺序是依据id号的从大到小，即后提交的活动出现在列表前面

**Comment by TXZdream** [comment]
上述问题接口已经修改，本地运行正常

**Comment by iamxiaoyubei** [comment]
第二个问题：获取活动列表API：https://www.sysuactivity.com/api/act?page={pagenum}&verify={verified} 并没有根据verified进行筛选，verify参数为0时仍然能verified为1的活动；
第三个问题：pagenum不同时返回的列表还是一样，我发布了超过10个活动的。

**Comment by TXZdream** [comment]
查明为pagenum参数解析问题，未认真看接口，以为还是pageNum参数。

关于verify参数，本地测试并无描述错误
