### ISSUE TITLE
第三次后端开发

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/service-end#6]
## 新的API
- [x]  注册API，请参考**注册API说明**

- [x]  登陆API，请参考**登陆API说明**

- [x]  图片上传API，请参考**图片上传API说明**

## 其他API加入权限访问控制

- [x]  请参考 **技术说明文档**，需要给五个API加入权限访问控制

## 旧API修改
- [x]  Modify Activity Info By Manager的API的request中减少了club字段请修改

- [x] 发布活动API和数据库均进行了修改，请参考 **技术说明文档**+**er图**+**api文档**

## 后台文件合法性检查

- [ ] 后台的图片类型检查

**Comment by TXZdream** [comment]
@iamxiaoyubei 数据库和小程序端使用的时同一个数据库，数据库的修改不应该在这里单方面进行，需要与小程序端进行沟通完成，这里的修改不是很麻烦，我这边直接修改。如果是添加字段，则问题不大，但是如果修改或者删除字段，一定要记得和小程序端沟通

**Comment by iamxiaoyubei** [comment]
按照小程序那边之前的er图来看，并没有删减字段，仅增加修改字段
