### ISSUE TITLE
第三次迭代后台验收测试

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/service-end#7]
## 未通过测试
- [x] PC User login API 出现500错误，POST https://www.sysuactivity.com/api/session ，Authorization头部传递的是token_string也不应该出现500吧

- [x] PC User Collection / PC User Sign up POST https://www.sysuactivity.com/api/pcusers ,  
`{
    "name": "组织名称",
    "email": "394634397@qq.com",
    "logo": "7ec0efa87bd5220313be8eed70f39192.jpg",
    "evidence": "7ec0efa87bd5220313be8eed70f39192.jpg",
    "info": "备注信息"
}`
出现400错误，上面图片是upload提交了的图片返回的文件名

- [x] Publish a New Activity 这个204是什么原因
{
        "name": "sample",
        "startTime": "yyyy-MM-dd hh:mm",
        "endTime": "yyyy-MM-dd hh:mm",
        "location":"三饭小广场",
        "campus":1,
        "enrollCondition":"计算机学院全体学生",
        "sponsor":"SDCS团委",
        "type":0,
        "pubStartTime": "yyyy-MM-dd hh:mm",
        "pubEndTime": "yyyy-MM-dd hh:mm",
        "detail":"飞扬C调是计算机学院的传统活动，2018年即将迎来第11个年头；往届比赛中，无数的歌声给我们带来了很多的精彩回忆！Coding&Singing，一起来吧！",
        "enrollWay":"报名方式：如短信报名，可以为空",
        "enrollEndTime": "yyyy-MM-dd hh:mm",
        "reward":"奖励可以为空",
        "introduction":"简介,可以为空",
        "requirement":"活动要求可以为空",
        "poster":"上传的海报的返回文件名，仅能上传一张海报，限制大小5m",
        "qrcode":"上传的二维码的返回文件名，仅能上传一张海报，限制大小5m",
        "can_enrolled":0,
        "email":"394634397@qq.com",
        "pcuser_id":null
}

- [x] 文档中要求了有其他的五个API需要加上访问控制，并没有添加

- [x] 请仔细查看这一次的迭代文档，这次的技术说明文档里面写了许多细节要求，请校对是否完成，比如自动登陆等等

## 通过测试

- Picture Collection / Upload a picture

**Comment by TXZdream** [comment]
enrollendtime并未在小程序端数据库给出，这里不予更改，即前端发送的endtime不会被计入数据库

**Comment by iamxiaoyubei** [comment]
当初小程序设计数据库时是因为说当次迭代目前不需要所以才删减了一些字段的，后续迭代需要的话会慢慢加上去。目前在PC端这个字段还是比较重要的，因为公众号推送一般都有放报名截止时间enrollendtime，因此望更改。

**Comment by TXZdream** [comment]
目前建议将该部分的更改记录下来，并连同小程序端一同更改，这里的更改会对数据库造成影响，从而相关的字段也需要更改，建议抽出一个迭代专门进行相关工作，不建议这里进行

**Comment by TXZdream** [comment]
另，问题三并不是数据库字段更改导致，而是时间格式导致，已修正

**Comment by TXZdream** [comment]
权限控制问题在文档的相关issue中有提出
另，自动登录是前端负责的内容，后台并不能进行状态的保留，自动登录只能后台提供给api接口验证方式

**Comment by iamxiaoyubei** [comment]
1. 可以
2. 好
3. 我说的自动登陆不是指状态保留，只是一个指代，就是后端提供api，api的header中需包含token，就是希望让你去注意下文档的细节

**Comment by TXZdream** [comment]
已经加入了权限控制，请求测试

**Comment by iamxiaoyubei** [comment]
## 未通过测试

- [x] 发布活动：请查看API文档和技术文档，第三次的设计是将发布活动API的权限由前端决定，是没有传token给后端的，因此关于pcuser_id那个问题，在前端传过来也是为了标示的，因为设计时是不考虑传token过来的，可以进行讨论

- [x]  修改活动信息API，以下500
```
{
        "name": "sample",
        "startTime": "2018-12-21 12:11",
        "endTime": "2018-12-21 12:11",
        "location":"三饭小广场",
        "campus":1,
        "enrollCondition":"计算机学院全体学生",
        "sponsor":"SDCS团委",
        "type":0,
        "pubStartTime": "2018-12-21 12:11",
        "pubEndTime": "2018-12-21 12:11",
        "detail":"飞扬C调是计算机学院的传统活动，2018年即将迎来第11个年头；往届比赛中，无数的歌声给我们带来了很多的精彩回忆！Coding&Singing，一起来吧！",
        "enrollWay":"报名方式：如短信报名，可以为空",
        "enrollEndTime": "2018-12-21 12:11",
        "reward":"奖励可以为空",
        "introduction":"简介,可以为空",
        "requirement":"活动要求可以为空",
"poster":"7ec0efa87bd5220313be8eed70f39192.jpg",
    "qrcode":"7ec0efa87bd5220313be8eed70f39192.jpg",
        "can_enrolled":0,
        "email":"394634397@qq.com"
}
```
## 通过测试

-  上传图片
-  注册API可用
-  登陆API通过测试：可利用token自动登陆+可无token或token错误情况下利用account登陆
-  列活动列表：可以权限拦截+管理员使用可以返回正确的活动列表(verified与page参数均成功)
-  活动详情：可以权限拦截+管理员使用可以返回正确的活动详情
-  审核活动：可以权限拦截+管理员使用审核
## 一点小问题

- [ ]  https://sysuactivity.com/static/7ec0efa87bd5220313be8eed70f39192.jpg 无法返回图片，此文件名为登陆时返回的管理员logo文件名

- [x] 管理员的name请改为"中大活动后台管理员"谢谢

- [x]  活动详情：返回属性中相对于API文档多了一个pcuser_id属性，是否需要？也可以要

**Comment by TXZdream** [comment]
1. 那个json的时间格式貌似是不合法的，你发的不会是`yyyy-mm-dd hh:mm`吧？如果是的话，请使用一个正常的时间，而不是字母
2. 返回图片问题我回去改，可能写入文件时出现的问题，即文件创建但并未正常写入
3. 这个只是测试使用的，后台生产环境是需要清空数据库重建的，已修改
4. 活动详情返回属性由于和创建用户使用的是同一个结构体，因此在生成json格式时，会被赋予默认值，若创建活动时可以取消pcuser_id的参数传递，则此处的属性会自动消失
这里提一个意见，因为在实际生产活动中的数据量胡更大，因此需要尽可能去压缩数据，也就是说传递的数据一定是必要的，即使一个空格也最好不要多传，所以pcuser_id如果需要的话，就加，不需要，就一定不要添加

**Comment by TXZdream** [comment]
经检查是编写代码时对nil指向的地址赋值的原因，已解决

**Comment by iamxiaoyubei** [comment]
发布活动：请查看API文档和技术文档，第三次的设计是将发布活动API的权限由前端决定，是没有传token给后端的，因此关于pcuser_id那个问题，在前端传过来也是为了标示的，因为设计时是不考虑传token过来的，可以进行讨论

**Comment by TXZdream** [comment]
前端传值会存在前端恶意传值问题吧？比如一个匿名用户传送的id为管理员id之类的？这个没法保证吧

**Comment by TXZdream** [comment]
已根据接口文档修改，但是实现上存在问题，已在技术文档issue提及，请进行确认

**Comment by TXZdream** [comment]
已修改图片上传接口，由于本地没有图片，所以使用文本文件作为测试的文件，请测试

**Comment by TXZdream** [comment]
上次迭代检查是否通过？通过的话关一下issue

**Comment by iamxiaoyubei** [comment]
我看到**一点小问题**那儿你还没有打勾，所以以为你还没有完成这两个问题。
其他打勾的都测试过了，通过。
然后我刚刚测了你那两个，出了问题。
https://www.sysuactivity.com/api/act/71 发生了504，以及用其他的活动id也是504
包括用postman测试上传活动也出现了timeout问题

**Comment by iamxiaoyubei** [comment]
静态服务器的文件还是不行 https://sysuactivity.com/static/7ec0efa87bd5220313be8eed70f39192.jpg

**Comment by iamxiaoyubei** [comment]
通过测试
