### ISSUE TITLE
第四次后端开发

### ISSUE THREAD

**Issue by iamxiaoyubei** [SYSU-ActivityPlusPC/service-end#9]
@TXZdream 需完成**注册申请和查看社团信息**中的三个API以及相关的技术
- [x] PC User List

- [x] Audit PC User By Manager

- [x] Get detailed PC User information

@iamxiaoyubei 需完成**通知社团**中的四个API以及相关数据库表的构建

- [x] Publish a New Message

- [x] List required messages 

- [x] Delete Message By Manager 

- [x] Get detailed message information

请于 6月3日晚23：39之前完成，并且确保本地和服务端进行了基本的测试，之后再进行验收测试

**Comment by TXZdream** [comment]
消息队列相关还没有本地测试，其余已经完成本地测试 @iamxiaoyubei

**Comment by TXZdream** [comment]
消息队列内容已完成本地测试 @iamxiaoyubei 
基本内容已全部完成，可以测试

**Comment by TXZdream** [comment]
@iamxiaoyubei 已完成基本的服务端测试，考虑服务端负载，已经关闭了消息队列，因此邮件发送可能不正常，但是本地已经完成测试，邮件发送功能一切正常，若需要修改架构，请参照我在服务端发送的最新issue进行考虑，从而在当前的资源范围内完成本次迭代

**Comment by iamxiaoyubei** [comment]
通知社团中的四个API以及相关数据库表的构建：
已完成本地和服务端测试通过

**Comment by TXZdream** [comment]
已完成服务端测试，邮件发送问题已解决 @iamxiaoyubei
